---
# Configuration for the pr-labeler workflow.

area/bot:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/__main__.py
              - roll35/bot.py
              - roll35/cogs/*.py
              - roll35/cogs/**/*.py

area/common:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/__init__.py
              - roll35/common.py

area/data-handling:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/data/*.py
              - roll35/data/**/*.py

area/parser:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/parser.py

area/renderer:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/renderer.py
              - roll35/types/render*.py

area/roller:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/roller/*.py
              - roll35/roller/**/*.py

area/scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - scripts/*
              - scripts/**/*

area/types:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/types/*.py
              - roll35/types/**/*.py

dataset:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - roll35/data/files/*
              - roll35/data/files/**/*

documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - LICENSE.md
              - README.md

infra:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .gigignore
              - .gitmodules
              - .github/labeler.yml
              - .github/labels.yml

infra/ci:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - scripts/check-labels.py
              - .flake8
              - .github/dependabot.yml
              - .github/workflows/**
              - .mdl-style.rb
              - .yamllint.yml

infra/packaging:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - Dockerfile
              - poetry.lock
              - pyproject.toml
