---
# Configuration for the pr-labeler workflow.

area/bot:
  - roll35/__main__.py
  - roll35/cogs/*.py
  - roll35/cogs/**/*.py

area/common:
  - roll35/__init__.py
  - roll35/common.py

area/data-handling:
  - roll35/data/*.py
  - roll35/data/**/*.py

area/parser:
  - roll35/parser.py

area/renderer:
  - roll35/renderer.py
  - roll35/types/render*.py

area/scripts:
  - scripts/*
  - scripts/**/*

area/types:
  - roll35/types/*.py
  - roll35/types/**/*.py

dataset:
  - roll35/data/files/*
  - roll35/data/files/**/*

documentation:
  - LICENSE.md
  - README.md

infra:
  - .gigignore
  - .gitmodules
  - .github/labeler.yml
  - .github/labels.yml

infra/ci:
  - scripts/check-labels.py
  - .flake8
  - .github/dependabot.yml
  - .github/workflows/**
  - .mdl-style.rb
  - .yamllint.yml

infra/packaging:
  - Dockerfile
  - requirements.txt
