---

extends: default

rules:
  colons:
    max-spaces-after: 6
  document-end:
    present: false
  indentation:
    spaces: 2
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
