---
name: Docker

on:
  pull_request:
    branch: main

jobs:
  build:
    name: Build ${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - linux/386
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: false
          platforms: ${{ matrix.arch }}
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}:test
