---
name: Docker

on:
  pull_request:
    branch: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.exs')) }}-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{
            hashfiles(format('{0}{1}', github.workspace, '/Dockerfile')) }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v2
        with:
          push: false
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: test
          cache-from: type=local,src=/tmp/.buildx-cache,mode=max
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache{-new,}
