---
name: Docker Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "tag='$(git describe --tags --abbrev 0)'" >> $GITHUB_ENV
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ secrets.DOCKER_IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.tag }}
      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ secrets.DOCKER_IMAGE_NAME }}
