---
name: Elixir

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  compile-check:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: setup
        with:
          elixir-version: 1.11.x
          otp-version: 23.3.x
      - uses: actions/cache@v2.1.7
        id: cache
        with:
          path: deps
          key: >-
            ${{ runner.os }}-mix-${{
            steps.setup.outputs.elixir-version }}-${{
            steps.setup.outputs.otp-version }}-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix deps.get
        if: steps.cache.outputs.cache-hit != true
      - run: mix compile --force
  format-check:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.11.x
          otp-version: 23.3.x
      - run: mix format --check-formatted
  test-suite:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: setup
        with:
          elixir-version: 1.11.x
          otp-version: 23.3.x
      - uses: actions/cache@v2.1.7
        id: cache
        with:
          path: deps
          key: >
            ${{ runner.os }}-mix-${{
            steps.setup.outputs.elixir-version }}-${{
            steps.setup.outputs.otp-version }}-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix deps.get
        if: steps.cache.outputs.cache-hit != true
      - run: mix test
  dialyxir:
    name: Dialyxir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: setup
        with:
          elixir-version: 1.11.x
          otp-version: 23.3.x
      - uses: actions/cache@v2.1.7
        id: cache
        with:
          path: deps
          key: >-
            ${{ runner.os }}-mix-${{
            steps.setup.outputs.elixir-version }}-${{
            steps.setup.outputs.otp-version }}-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix deps.get
        if: steps.cache.outputs.cache-hit != true
      - uses: actions/cache@v2.1.7
        with:
          path: _build/**/*.plt
          key: >-
            ${{ runner.os }}-dialyxir-${{
            steps.setup.outputs.elixir-version }}-${{
            steps.setup.outputs.otp-version }}-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-dialyxir-
      - run: mix dialyzer
