---
name: Elixir

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  compile-check:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.11.x
          otp-version: 23.1.x
      - run: mix deps.get
      - run: mix compile --force
  format-check:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.11.x
          otp-version: 23.1.x
      - run: mix format --check-formatted
  test-suite:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.11.x
          otp-version: 23.1.x
      - run: mix deps.get
      - run: mix test
