---
name: Sync Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
      - .github/workflows/label-sync.yaml

concurrency:
  group: label-sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
