---
name: Publish Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: publish-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.repository == 'Ferroin/Roll35'
    steps:
      - uses: actions/checkout@v3
      - id: tags
        run: |
          version="$(git describe --tags | cut -f 1 -d '-')"
          echo "tags=ahferroin7/roll35:latest,$(scripts/gen-docker-tags.py '${version}' ahferroin7/roll35)" >> "${GITHUB_OUTPUT}"
          echo "version=${version}" >> "${GITHUB_OUTPUT}"
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ steps.tags.outputs.tag }}
          tags: ${{ steps.tags.outputs.tag }}
