---
name: Publish Edge

on:
  push:
    branches:
      - main

concurrency:
  group: publish-edge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    if: github.repository == 'Ferroin/Roll35'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=edge
          tags: ahferroin7/roll35:edge,ahferroin7/roll35:latest
