---
name: Publish Edge

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Surgo/docker-smart-tag-action@v1
        id: tag_detection
        with:
          docker_image: ahferroin7/roll35
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.exs')) }}-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}-${{
            hashfiles(format('{0}{1}', github.workspace, '/Dockerfile')) }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.tag_detection.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache,mode=max
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
