---
name: ReviewDog

on:
  pull_request:
    branch: main

jobs:
  credo:
    name: Credo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.11.x
          otp-version: 23.1.x
      - run: mix deps.get
      - uses: red-shirts/reviewdog-action-credo@v1.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
